const taskData = [
  {
    title: "Wednesday, 20 March, 2024",
    data: [
      { id: 1, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
      { id: 2, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
      { id: 3, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
      { id: 4, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
      { id: 5, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
      { id: 6, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
      { id: 7, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
      { id: 8, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
      { id: 9, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
      { id: 10, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
      { id: 11, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
      { id: 12, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
    ],
  },
  {
    title: "Thusday, 21 March, 2024",
    data: [
      { id: 1, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
      { id: 2, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
      { id: 3, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
      { id: 4, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
      { id: 5, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
      { id: 6, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
      { id: 7, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
      { id: 8, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
      { id: 9, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
      { id: 10, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
      { id: 11, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
      { id: 12, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
    ],
  },
  {
    title: "Friday, 22 March, 2024",
    data: [
      { id: 1, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
      { id: 2, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
      { id: 3, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
      { id: 4, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
      { id: 5, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
      { id: 6, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
      { id: 7, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
      { id: 8, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
      { id: 9, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
      { id: 10, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
      { id: 11, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
      { id: 12, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
    ]},
    {
      title: "Friday, 29 March, 2024",
      data: [
        { id: 1, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
        { id: 2, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
        { id: 3, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
        { id: 4, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
        { id: 5, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
        { id: 6, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
        { id: 7, time: '10:00', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
        { id: 8, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
        { id: 9, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
        { id: 10, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
        { id: 11, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
        { id: 12, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
      ],
    },
    {
      title: "Sunday, 31 March, 2024",
      data: [
        { id: 1, time: '15:30', title: 'Meeting with Johnny', type: 'Official', starred: false, color: 'red' },
        { id: 2, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
        { id: 3, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
        { id: 4, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
        { id: 5, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
        { id: 6, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
        { id: 7, time: '10:20', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
        { id: 8, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
        { id: 9, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
        { id: 10, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
        { id: 11, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
        { id: 12, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
      ],
    },
    {
      title: "Monday, 1 April, 2024",
      data: [
        { id: 1, time: '20:00', title: 'Meeting with Henry', type: 'Official', starred: false, color: 'red' },
        { id: 2, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
        { id: 3, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
        { id: 4, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
        { id: 5, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
        { id: 6, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
        { id: 7, time: '10:25', title: 'Meeting with client', type: 'Official', starred: false, color: 'red' },
        { id: 8, time: '11:00', title: 'Lauch with July', type: 'Family', starred: false, color: 'blue' },
        { id: 9, time: '12:30', title: 'Meet Joshep', type: 'Friend', starred: false, color: 'orange' },
        { id: 10, time: '13:00', title: 'Daily meeting', type: 'Official', starred: false, color: 'green' },
        { id: 11, time: '15:00', title: 'Lauch with Johny', type: 'Family', starred: false, color: 'red' },
        { id: 12, time: '17:30', title: 'Reading book', type: 'Friend', starred: false, color: 'orange' },
      ],
    },
  ];
  
  export default taskData;
  